name: deploy order order-backend

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout github
        uses: actions/checkout@v4

      - name: install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: "v1.25.9"

      - name: configure aws
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET }}
          aws-region: ap-northeast-2

      - name: update cluster information
        run: aws eks update-kubeconfig --name kbh-team-cluster --region ap-northeast-2

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --region ap-northeast-2 --name kbh-team-cluster

      - name: create namespace
        run: |
          kubectl create namespace soldesk --dry-run=client -o yaml | kubectl apply -f -
          kubectl create namespace argocd --dry-run=client -o yaml | kubectl apply -f -
          kubectl create namespace monitoring --dry-run=client -o yaml | kubectl apply -f -

      - name: DB secret
        run: |
          kubectl create secret generic my-app-secrets \
          --from-literal=DB_HOST=kbh-team-rds-mysql.clo62q46ww0g.ap-northeast-2.rds.amazonaws.com \
          --from-literal=DB_PW='admin1234' \
          -n soldesk \
          --dry-run=client -o yaml | kubectl apply -f -

      - name: aws secret
        run: |
          kubectl create secret generic aws-secret \
          --from-literal=AWS_ACCESS_KEY_ID="$S3_AWS_ACCESS_KEY_ID" \
          --from-literal=AWS_SECRET_ACCESS_KEY="$S3_AWS_SECRET_ACCESS_KEY" \
          -n soldesk \
          --dry-run=client -o yaml | kubectl apply -f -
        env:
          S3_AWS_ACCESS_KEY_ID: ${{ secrets.AWS_S3_ACCESS_KEY_ID }}
          S3_AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY }}
      
      - name: install ingress-nginx controller
        run: |
          kubectl apply  -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.8.1/deploy/static/provider/aws/deploy.yaml

      - name: install cert-manager
        run: |
          kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.19.4/cert-manager.yaml

      - name: install metrics-server
        run: |
          kubectl apply -f https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml

      - name: install argo-cd
        run: |
          kubectl apply -n argocd --server-side -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml

      - name: wait for argocd crds
        run: |
          kubectl wait --for=condition=Established --timeout=180s crd/applications.argoproj.io


      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: detect changed services
        id: changes
        uses: dorny/paths-filter@v3
        with:
          filters: |
            gateway:
              - 'msa/apigateway/**'
            member:
              - 'msa/member/**'
            ordering:
              - 'msa/ordering/**'
            product:
              - 'msa/product/**'
            frontend:
              - 'msa/frontend/**'
            shared_k8s:
              - 'msa/k8s/**'
            argocd:
              - 'argocd/**'

      - name: stop if no service changed
        if: |
          steps.changes.outputs.gateway != 'true' &&
          steps.changes.outputs.member != 'true' &&
          steps.changes.outputs.ordering != 'true' &&
          steps.changes.outputs.product != 'true' &&
          steps.changes.outputs.frontend != 'true' &&
          steps.changes.outputs.shared_k8s != 'true' &&
          steps.changes.outputs.argocd != 'true'
        run: |
          echo "No deploy-related directory changed."
          exit 0

      - name: apply shared kubernetes manifests
        # if: steps.changes.outputs.shared_k8s == 'true'
        run: |
          kubectl apply -R -f ./msa/k8s

      - name: apply argocd manifests
        # if: steps.changes.outputs.argocd == 'true'
        run: |
          kubectl apply -R -f ./argocd/apps
          
      - name: gateway build and push docker image to ecr
        # if: steps.changes.outputs.gateway == 'true'
        env:
          REGISTRY: 683668078297.dkr.ecr.ap-northeast-2.amazonaws.com
          REPOSITORY: kbh-apigateway
          IMAGE_TAG: latest
        run: |
          docker build \
            -t $REGISTRY/$REPOSITORY:$IMAGE_TAG \
            -f ./msa/apigateway/Dockerfile ./msa/apigateway
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

      - name: deploy gateway
        # if: steps.changes.outputs.gateway == 'true'
        run: |
          kubectl apply -f ./msa/apigateway/k8s/depl_svc.yml
          kubectl rollout restart deployment apigateway-depl -n soldesk

      - name: member build and push docker image to ecr
        # if: steps.changes.outputs.member == 'true'
        env:
          REGISTRY: 683668078297.dkr.ecr.ap-northeast-2.amazonaws.com
          REPOSITORY: kbh-member-service
          IMAGE_TAG: latest
        run: |
          docker build \
            -t $REGISTRY/$REPOSITORY:$IMAGE_TAG \
            -f ./msa/member/Dockerfile ./msa/member
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

      - name: deploy member
        # if: steps.changes.outputs.member == 'true'
        run: |
          kubectl apply -f ./msa/member/k8s/depl_svc.yml
          kubectl rollout restart deployment member-depl -n soldesk

      - name: order build and push docker image to ecr
        # if: steps.changes.outputs.ordering == 'true'
        env:
          REGISTRY: 683668078297.dkr.ecr.ap-northeast-2.amazonaws.com
          REPOSITORY: kbh-ordering-service
          IMAGE_TAG: latest
        run: |
          docker build \
            -t $REGISTRY/$REPOSITORY:$IMAGE_TAG \
            -f ./msa/ordering/Dockerfile ./msa/ordering
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

      - name: deploy ordering
        # if: steps.changes.outputs.ordering == 'true'
        run: |
          kubectl apply -f ./msa/ordering/k8s/depl_svc.yml
          kubectl rollout restart deployment ordering-depl -n soldesk

      - name: product build and push docker image to ecr
        # if: steps.changes.outputs.product == 'true'
        env:
          REGISTRY: 683668078297.dkr.ecr.ap-northeast-2.amazonaws.com
          REPOSITORY: kbh-product-service
          IMAGE_TAG: latest
        run: |
          docker build \
            -t $REGISTRY/$REPOSITORY:$IMAGE_TAG \
            -f ./msa/product/Dockerfile ./msa/product
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

      - name: deploy product
        # if: steps.changes.outputs.product == 'true'
        run: |
          kubectl apply -f ./msa/product/k8s/depl_svc.yml
          kubectl rollout restart deployment product-depl -n soldesk

      - name: frontend build and push docker image to ecr
        # if: steps.changes.outputs.frontend == 'true'
        env:
          REGISTRY: 683668078297.dkr.ecr.ap-northeast-2.amazonaws.com
          REPOSITORY: kbh-frontend-service
          IMAGE_TAG: latest
        run: |
          docker build \
            -t $REGISTRY/$REPOSITORY:$IMAGE_TAG \
            -f ./msa/frontend/Dockerfile ./msa/frontend
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

      - name: deploy frontend
        # if: steps.changes.outputs.frontend == 'true'
        run: |
          kubectl apply -f ./msa/frontend/k8s/depl_svc.yml
          kubectl rollout restart deployment frontend-depl -n soldesk



      - name: autoscaler apply
        run: |
          kubectl apply -R -f ./msa/k8s/autoscaler


      - name: apply argocd manifests
        # if: steps.changes.outputs.argocd == 'true'
        run: |
          kubectl apply -f ./argocd/root-app.yml
